// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rodar-espera/CampoDeOndas.tsx": () => import("../components/mockups/rodar-espera/CampoDeOndas.tsx"),
  "./components/mockups/rodar-espera/FluxoVivo.tsx": () => import("../components/mockups/rodar-espera/FluxoVivo.tsx"),
  "./components/mockups/rodar-espera/NucleoOrbital.tsx": () => import("../components/mockups/rodar-espera/NucleoOrbital.tsx")
};
